# Generated by Django 6.0.3 on 2026-03-31 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Attraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('attraction_type', models.CharField(choices=[('ride', 'Ride'), ('show', 'Show'), ('experience', 'Experience'), ('dining', 'Dining')], default='ride', max_length=20)),
                ('thrill_level', models.IntegerField(choices=[(1, 'Mild - All Ages'), (2, 'Moderate - Some Thrills'), (3, 'Thrilling - Not for the Faint of Heart'), (4, 'Extreme - Hold onto Your Ewok!')], default=1)),
                ('min_height_cm', models.IntegerField(default=0)),
                ('duration_minutes', models.IntegerField(default=5)),
                ('current_wait_minutes', models.IntegerField(default=0)),
                ('is_operational', models.BooleanField(default=True)),
                ('fastpass_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attractions', to='fastpass.themezone')),
            ],
            options={
                'ordering': ['zone', 'name'],
            },
        ),
    ]
