# Generated by Django 6.0.3 on 2026-03-31 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fastpass', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('membership_tier', models.CharField(choices=[('standard', 'Standard - Day Pass'), ('silver', 'Silver - Season Pass'), ('gold', 'Gold - Premium Season Pass'), ('platinum', 'Platinum - VIP All-Access')], default='standard', max_length=20)),
                ('daily_fastpass_limit', models.IntegerField(default=3)),
                ('height_cm', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('max_fastpasses', models.IntegerField(default=50)),
                ('is_active', models.BooleanField(default=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='fastpass.attraction')),
            ],
            options={
                'ordering': ['attraction', 'start_time'],
                'unique_together': {('attraction', 'start_time')},
            },
        ),
        migrations.CreateModel(
            name='FastPass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('used', 'Used'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], default='confirmed', max_length=20)),
                ('booked_at', models.DateTimeField(auto_now_add=True)),
                ('attraction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastpasses', to='fastpass.attraction')),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastpasses', to='fastpass.guest')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fastpasses', to='fastpass.timeslot')),
            ],
            options={
                'verbose_name_plural': 'FastPasses',
                'ordering': ['-booking_date', 'time_slot__start_time'],
                'unique_together': {('guest', 'attraction', 'booking_date')},
            },
        ),
    ]
